---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polymesh.fullname" . }}-reserved-peers
data:
  reserved_peers.txt: |
    {{- range .Values.reservedPeers }}
    {{ . }}
    {{- end }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "polymesh.fullname" . }}-set-operator-keys
data:
  setKeys.sh: |
    #!/bin/bash
    set -e
    set -x
    set -o pipefail

    cp /operator-keys/* /operator-keys-ephemeral/

