{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "polymesh.fullname" . }}
  labels:
    {{- include "polymesh.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  {{- $fullname := include "polymesh.fullname" . -}}
  {{- $root := . -}}
  {{- range $key, $value := .Values.ingress.hosts }}
    - host: {{ $value.host }}
      http:
        paths:
          - path: "{{ default "" .pathPrefix }}/http"
            pathType: Exact
            backend:
              service:
                name: {{ $fullname }}-jsonrpc
                port:
                  number: {{ $root.Values.service.jsonrpc.port }}
          - path: "{{ default "" .pathPrefix }}/"
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-wsrpc
                port:
                  number: {{ $root.Values.service.wsrpc.port }}
  {{- end }}
  tls:
    {{- range .Values.ingress.hosts }}
    {{- if .tlsSecret }}
    - hosts:
        - {{ .host }}
      secretName: {{ .tlsSecret }}
    {{- end }}
    {{- end }}
{{- end }}

